version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
        - ConnectionStrings__MySQLIdentity=${ConnectionStrings__MySQLIdentity}
        - MongoDbSettings__ConnectionString=${MongoDbSettings__ConnectionString}
        - MongoDbSettings__DatabaseName=${MongoDbSettings__DatabaseName}
    volumes:
      - dataprotection-keys:/app/dataprotection-keys
    
volumes:
  dataprotection-keys:
  mysql-data:
  mongo-data:
